services:
  db:
    image: postgres:11.0
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasklist
    ports:
      - 5432:5432
volumes:
  pgdata:
